config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "gossip#home"
  get '/gossip/:id', to: "gossip#gossip", as: "gossip/id"
  get '/team', to: 'team#team'
  get '/contact', to: 'contact#contact'
  get '/welcome/:name', to: 'welcome#welcome'
  get '/user/:id', to: "user#user", as: "user/id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users

end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, optional: true
    has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
    def home
        @gossips = Gossip.all 
    end
    def gossip
        @gossips = Gossip.all
    end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    def team
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def welcome
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/contact.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
 <%= link_to 'Gossips', '/', class: 'navbar-brand' %>   
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', '/', class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Contact', '/contact', class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Team', '/team', class: 'nav-link' %>
        </li>
       
      </ul>
    </div>
  </div>
</nav>

<section class="container">
<h1>Voici la page Contact</h1>
      <div class="border border-2 rounded-3 border-primary m-3 p-3 col-4">
    Pour contacter  
</div>
</section>

app/views/gossip/gossip.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
 <%= link_to 'Gossips', '/', class: 'navbar-brand' %>   
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', '/', class: 'nav-link active' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Contact', '/contact', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Team', '/team', class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<section class="container">
     <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Gossip preview-->
                    <% gossip=Gossip.find(params[:id])%>
                    <div class="post-preview">
                      <h1 class="post-title"><%= gossip.title %></h1>
                      <p class="post-subtitle"><%= gossip.content %></p>
                      <em class="post-meta">
                      Posted by
                      <%= link_to User.find(gossip.user_id).first_name, user_id_path(gossip.user_id),class: 'link-dark' %>
                      , <%= gossip.created_at %>
                      </em>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                </div>
            </div>
      </div>

</section>

                    <em>2021 - THE GOSSIP PROJECT </em>

app/views/gossip/home.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
 <%= link_to 'Gossips', '/', class: 'navbar-brand' %>   
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', '/', class: 'nav-link active' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Contact', '/contact', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Team', '/team', class: 'nav-link' %>
        </li>
       
      </ul>
    </div>
  </div>
</nav>
 <header class="header blur-2" >
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="site-heading">
          <br/>
            <h1>Bienvenue sur GOSSIP PROJECT</h1>
            <span class="subheading">Ici c'est notre super site de potins, il est chouette, non ?</span>
          </div>
        </div>
      </div>
    </div>
  </header>
<section class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Gossip preview-->
      <div class="post-preview">
      <br/>
        <% @gossips.each do |gossip|%>
          <h2 class="post-title display-4"> <%= gossip.title %></h2>
          <h3 class="post-subtitle"><i class="blockquote">by: <%= User.find(gossip.user_id).first_name %></i></h3>
          <%= link_to "voir plus", gossip_id_path(gossip.id),class: 'link-dark' %>
          <hr class="my-4" />
        <% end %> 
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S5GossipsRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/team/team.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
 <%= link_to 'Gossips', '/', class: 'navbar-brand' %>   
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', '/', class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Contact', '/contact', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Team', '/team', class: 'nav-link active' %>
        </li>
       
      </ul>
    </div>
  </div>
</nav>
<section class="container">
<h1>La team</h1>
      <div class="border border-2 rounded-3 border-primary m-3 p-3 col-4">
   voici notre équipe lol mdr 😇❤️😻
</div>
</section>

app/views/user/user.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
 <%= link_to 'Gossips', '/', class: 'navbar-brand' %>   
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', '/', class: 'nav-link active' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Contact', '/contact', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Team', '/team', class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<section class="wrapper">
  <div class="container">
      <div class="row">
        <div class="col-sm-12">
            <div class="card text-light card-has-bg click-col" style="background-image:url('https://source.unsplash.com/600x900/?tech,street');">
            <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tech,street" alt="Goverment Lorem Ipsum Sit Amet Consectetur dipisi?">
                <div class="card-img-overlay d-flex flex-column">
                    <div class="card-body">
                     <% user=User.find(params[:id])%>
                        <small class="card-meta mb-2"><%= user.first_name %> <%= user.last_name %></small>
                        <h4 class="card-title mt-0 text-light" ><%= user.description %></h4>
                        <small><i class="far fa-clock"></i> <%= user.email %></small>
                        <small><i class="far fa-clock"></i> <%= City.find(user.city_id).name %></small>

                    </div>
                    <div class="card-footer">
                        <div class="media">
                            <img class="mr-3 rounded-circle" src="https://cdn0.iconfinder.com/data/icons/user-pictures/100/male-512.png" alt="Generic placeholder image" style="max-width:50px">
                            <div class="media-body">
                                <h6 class="my-0 text-white d-block"><%= user.first_name %> <%= user.last_name %></h6>
                                    <small><%= user.created_at %></small>
                            </div>
                        </div>  
                    </div>
                </div>
        </div>
      </div>
  </div>
</section>

                    <em>2021 - THE GOSSIP PROJECT </em>

app/views/welcome/welcome.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
 <%= link_to 'Gossips', '/', class: 'navbar-brand' %>   
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', '/', class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Contact', '/contact', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Team', '/team', class: 'nav-link' %>
        </li>
       
      </ul>
    </div>
  </div>
</nav>
<section class="container">
<h1>La Page SECTRETE</h1>
      <div class="border border-2 rounded-3 border-primary m-3 p-3 col-4">
   😇❤️😻 BIENVENUE <%= params[:name] %> ! Ici c'est notre super site de potins, il est chouette, non ?
   
</div>
</section>